//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentJqGrid.Mvc4.Demo.SampleSources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SimpleLoad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SimpleLoad() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentJqGrid.Mvc4.Demo.SampleSources.SimpleLoad", typeof(SimpleLoad).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private readonly SrcSamples _srcSamples;
        ///private readonly IRepository&lt;Product&gt; _productRepository;
        ///
        ///public SimpleLoadController(SrcSamples srcSamples, IRepository&lt;Product&gt; productRepository)
        ///{
        ///    _srcSamples = srcSamples;
        ///    _productRepository = productRepository;
        ///}
        ///
        ///public ActionResult GetForJsonLoad(JqGridPost post)
        ///{
        ///    var product = new PagedList&lt;Product&gt;(
        ///        _productRepository.Table.OrderBy(m =&gt; m.ProductID), post.page, post.rows);
        ///
        ///    var jqRows = product.Select(item =&gt; new Grid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonLoad_Controller {
            get {
                return ResourceManager.GetString("JsonLoad_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JsonLoad_Description {
            get {
                return ResourceManager.GetString("JsonLoad_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table id=&quot;fjqgrid&quot;&gt;
        ///&lt;/table&gt;
        ///&lt;div id=&quot;pager&quot;&gt;
        ///&lt;/div&gt;
        ///@(Html.JqGrid()
        ///    .Name(&quot;fjqgrid&quot;)
        ///    .Url(&quot;/simpleload/getforjsonload&quot;)
        ///    .DataType(&quot;json&quot;)
        ///    .MType(&quot;GET&quot;)
        ///    .Columns(c =&gt;
        ///                 {
        ///                     c.Bind(&quot;ProductID&quot;).Header(&quot;ID&quot;);
        ///                     c.Bind(&quot;Name&quot;).Header(&quot;Name&quot;);
        ///                     c.Bind(&quot;Size&quot;).Header(&quot;Size&quot;).Align(ColumnAlign.Center);
        ///                     c.Bind(&quot;ProductCategoryID&quot;).Header(&quot;Category&quot;);
        ///                     c.Bind(&quot;ListPri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonLoad_View {
            get {
                return ResourceManager.GetString("JsonLoad_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private readonly SrcSamples _srcSamples;
        ///private readonly IRepository&lt;Product&gt; _productRepository;
        ///
        ///public SimpleLoadController(SrcSamples srcSamples, IRepository&lt;Product&gt; productRepository)
        ///{
        ///    _srcSamples = srcSamples;
        ///    _productRepository = productRepository;
        ///}
        ///
        ///public ActionResult StronglyTypedColumns()
        ///{
        ///    ViewData[&quot;src&quot;] = _srcSamples.SetSamples(SimpleLoad.JsonLoad_View, SimpleLoad.JsonLoad_Controller,
        ///                                                string.Empty);
        ///    return View(); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StronglyTypedColumns_Controller {
            get {
                return ResourceManager.GetString("StronglyTypedColumns_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StronglyTypedColumns_Description {
            get {
                return ResourceManager.GetString("StronglyTypedColumns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table id=&quot;fjqgrid&quot;&gt;
        ///&lt;/table&gt;
        ///&lt;div id=&quot;pager&quot;&gt;
        ///&lt;/div&gt;
        ///@(Html.JqGrid&lt;ProductModel&gt;()
        ///    .Name(&quot;fjqgrid&quot;)
        ///    .Url(&quot;/simpleload/getforstronglytypedcolumns&quot;)
        ///    .DataType(&quot;json&quot;)
        ///    .MType(&quot;GET&quot;)
        ///    .Columns(c =&gt;
        ///                 {
        ///                     c.Bind(m=&gt;m.ProductID).Header(&quot;ID&quot;);
        ///                     c.Bind(m =&gt; m.Name).Header(&quot;Name&quot;);
        ///                     c.Bind(m =&gt; m.Size).Header(&quot;Size&quot;).Align(ColumnAlign.Center);
        ///                     c.Bind(m =&gt; m.ProductCategoryID).Header(&quot;Categ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StronglyTypedColumns_View {
            get {
                return ResourceManager.GetString("StronglyTypedColumns_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private readonly SrcSamples _srcSamples;
        ///        private readonly IRepository&lt;Product&gt; _productRepository;
        ///
        ///        public SimpleLoadController(SrcSamples srcSamples, IRepository&lt;Product&gt; productRepository)
        ///        {
        ///            _srcSamples = srcSamples;
        ///            _productRepository = productRepository;
        ///        }
        ///
        ///                public ActionResult XmlLoad()
        ///        {
        ///            ViewData[&quot;src&quot;] = _srcSamples.SetSamples(SimpleLoad.XmlLoad_View, SimpleLoad.XmlLoad_Controller,
        ///                  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlLoad_Controller {
            get {
                return ResourceManager.GetString("XmlLoad_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string XmlLoad_Description {
            get {
                return ResourceManager.GetString("XmlLoad_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table id=&quot;fjqgrid&quot;&gt;
        ///&lt;/table&gt;
        ///&lt;div id=&quot;pager&quot;&gt;
        ///&lt;/div&gt;
        ///@(Html.JqGrid()
        ///    .Name(&quot;fjqgrid&quot;)
        ///    .Url(&quot;/simpleload/getforxmlload&quot;)
        ///    .DataType(&quot;xml&quot;)
        ///    .MType(&quot;GET&quot;)
        ///    .Columns(c =&gt;
        ///                 {
        ///                     c.Bind(&quot;ProductID&quot;).Header(&quot;ID&quot;);
        ///                     c.Bind(&quot;Name&quot;).Header(&quot;Name&quot;);
        ///                     c.Bind(&quot;Size&quot;).Header(&quot;Size&quot;).Align(ColumnAlign.Center);
        ///                     c.Bind(&quot;ProductCategoryID&quot;).Header(&quot;Category&quot;);
        ///                     c.Bind(&quot;ListPrice [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlLoad_View {
            get {
                return ResourceManager.GetString("XmlLoad_View", resourceCulture);
            }
        }
    }
}
