//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksLT.Data.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Address_Mapping : EntityTypeConfiguration<Address>
    {
        public Address_Mapping()
        {                        
              this.HasKey(t => t.AddressID);        
              this.ToTable("Address", "SalesLT");
              this.Property(t => t.AddressID).HasColumnName("AddressID");
              this.Property(t => t.AddressLine1).HasColumnName("AddressLine1").IsRequired().HasMaxLength(60);
              this.Property(t => t.AddressLine2).HasColumnName("AddressLine2").HasMaxLength(60);
              this.Property(t => t.City).HasColumnName("City").IsRequired().HasMaxLength(30);
              this.Property(t => t.StateProvince).HasColumnName("StateProvince").IsRequired().HasMaxLength(50);
              this.Property(t => t.CountryRegion).HasColumnName("CountryRegion").IsRequired().HasMaxLength(50);
              this.Property(t => t.PostalCode).HasColumnName("PostalCode").IsRequired().HasMaxLength(15);
              this.Property(t => t.rowguid).HasColumnName("rowguid");
              this.Property(t => t.ModifiedDate).HasColumnName("ModifiedDate");
         }
    }
}
