//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace AdventureWorksLT.Data.Data
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventureWorksLTEntities : DbContext
    {
        static AdventureWorksLTEntities()
    	{ 
    		Database.SetInitializer<AdventureWorksLTEntities>(null);
    	}
    	
    	public AdventureWorksLTEntities() : base("name=AdventureWorksLTEntities")
        {
        }
    	
    	public AdventureWorksLTEntities(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public AdventureWorksLTEntities(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public AdventureWorksLTEntities(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public AdventureWorksLTEntities(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {		
            //modelBuilder.Configurations.Add(new Address_Mapping());
            //modelBuilder.Configurations.Add(new BuildVersion_Mapping());
            //modelBuilder.Configurations.Add(new Customer_Mapping());
            //modelBuilder.Configurations.Add(new CustomerAddress_Mapping());
            //modelBuilder.Configurations.Add(new ErrorLog_Mapping());
            //modelBuilder.Configurations.Add(new Product_Mapping());
            //modelBuilder.Configurations.Add(new ProductCategory_Mapping());
            //modelBuilder.Configurations.Add(new ProductDescription_Mapping());
            //modelBuilder.Configurations.Add(new ProductModel_Mapping());
            //modelBuilder.Configurations.Add(new ProductModelProductDescription_Mapping());
            //modelBuilder.Configurations.Add(new SalesOrderDetail_Mapping());
            //modelBuilder.Configurations.Add(new SalesOrderHeader_Mapping());
        }
    	
        public DbSet<BuildVersion> BuildVersion { get; set; }
        public DbSet<ErrorLog> ErrorLog { get; set; }
        public DbSet<Address> Address { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<CustomerAddress> CustomerAddress { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductCategory> ProductCategory { get; set; }
        public DbSet<ProductDescription> ProductDescription { get; set; }
        public DbSet<ProductModel> ProductModel { get; set; }
        public DbSet<ProductModelProductDescription> ProductModelProductDescription { get; set; }
        public DbSet<SalesOrderDetail> SalesOrderDetail { get; set; }
        public DbSet<SalesOrderHeader> SalesOrderHeader { get; set; }
    }
}
