//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksLT.Data.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class BuildVersion_Mapping : EntityTypeConfiguration<BuildVersion>
    {
        public BuildVersion_Mapping()
        {                        
              this.HasKey(t => new {t.SystemInformationID, t.Database_Version, t.VersionDate, t.ModifiedDate});        
              this.ToTable("BuildVersion", "AdventureWorksLT2008R2ModelStoreContainer");
              this.Property(t => t.SystemInformationID).HasColumnName("SystemInformationID");
              this.Property(t => t.Database_Version).HasColumnName("Database Version").IsRequired().HasMaxLength(25);
              this.Property(t => t.VersionDate).HasColumnName("VersionDate");
              this.Property(t => t.ModifiedDate).HasColumnName("ModifiedDate");
         }
    }
}
