//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksLT.Data.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Customer_Mapping : EntityTypeConfiguration<Customer>
    {
        public Customer_Mapping()
        {                        
              this.HasKey(t => t.CustomerID);        
              this.ToTable("Customer", "SalesLT");
              this.Property(t => t.CustomerID).HasColumnName("CustomerID");
              this.Property(t => t.NameStyle).HasColumnName("NameStyle");
              this.Property(t => t.Title).HasColumnName("Title").HasMaxLength(8);
              this.Property(t => t.FirstName).HasColumnName("FirstName").IsRequired().HasMaxLength(50);
              this.Property(t => t.MiddleName).HasColumnName("MiddleName").HasMaxLength(50);
              this.Property(t => t.LastName).HasColumnName("LastName").IsRequired().HasMaxLength(50);
              this.Property(t => t.Suffix).HasColumnName("Suffix").HasMaxLength(10);
              this.Property(t => t.CompanyName).HasColumnName("CompanyName").HasMaxLength(128);
              this.Property(t => t.SalesPerson).HasColumnName("SalesPerson").HasMaxLength(256);
              this.Property(t => t.EmailAddress).HasColumnName("EmailAddress").HasMaxLength(50);
              this.Property(t => t.Phone).HasColumnName("Phone").HasMaxLength(25);
              this.Property(t => t.PasswordHash).HasColumnName("PasswordHash").IsRequired().IsUnicode(false).HasMaxLength(128);
              this.Property(t => t.PasswordSalt).HasColumnName("PasswordSalt").IsRequired().IsUnicode(false).HasMaxLength(10);
              this.Property(t => t.rowguid).HasColumnName("rowguid");
              this.Property(t => t.ModifiedDate).HasColumnName("ModifiedDate");
         }
    }
}
