//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksLT.Data.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class ProductDescription_Mapping : EntityTypeConfiguration<ProductDescription>
    {
        public ProductDescription_Mapping()
        {                        
              this.HasKey(t => t.ProductDescriptionID);        
              this.ToTable("ProductDescription", "SalesLT");
              this.Property(t => t.ProductDescriptionID).HasColumnName("ProductDescriptionID");
              this.Property(t => t.Description).HasColumnName("Description").IsRequired().HasMaxLength(400);
              this.Property(t => t.rowguid).HasColumnName("rowguid");
              this.Property(t => t.ModifiedDate).HasColumnName("ModifiedDate");
         }
    }
}
