//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksLT.Data.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class ProductCategory_Mapping : EntityTypeConfiguration<ProductCategory>
    {
        public ProductCategory_Mapping()
        {                        
              this.HasKey(t => t.ProductCategoryID);        
              this.ToTable("ProductCategory", "SalesLT");
              this.Property(t => t.ProductCategoryID).HasColumnName("ProductCategoryID");
              this.Property(t => t.ParentProductCategoryID).HasColumnName("ParentProductCategoryID");
              this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50);
              this.Property(t => t.rowguid).HasColumnName("rowguid");
              this.Property(t => t.ModifiedDate).HasColumnName("ModifiedDate");
              this.HasOptional(t => t.ProductCategory2).WithMany(t => t.ProductCategory1).HasForeignKey(d => d.ParentProductCategoryID);
         }
    }
}
