//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksLT.Data.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Product_Mapping : EntityTypeConfiguration<Product>
    {
        public Product_Mapping()
        {                        
              this.HasKey(t => t.ProductID);        
              this.ToTable("Product", "SalesLT");
              this.Property(t => t.ProductID).HasColumnName("ProductID");
              this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50);
              this.Property(t => t.ProductNumber).HasColumnName("ProductNumber").IsRequired().HasMaxLength(25);
              this.Property(t => t.Color).HasColumnName("Color").HasMaxLength(15);
              this.Property(t => t.StandardCost).HasColumnName("StandardCost");
              this.Property(t => t.ListPrice).HasColumnName("ListPrice");
              this.Property(t => t.Size).HasColumnName("Size").HasMaxLength(5);
              this.Property(t => t.Weight).HasColumnName("Weight");
              this.Property(t => t.ProductCategoryID).HasColumnName("ProductCategoryID");
              this.Property(t => t.ProductModelID).HasColumnName("ProductModelID");
              this.Property(t => t.SellStartDate).HasColumnName("SellStartDate");
              this.Property(t => t.SellEndDate).HasColumnName("SellEndDate");
              this.Property(t => t.DiscontinuedDate).HasColumnName("DiscontinuedDate");
              this.Property(t => t.ThumbNailPhoto).HasColumnName("ThumbNailPhoto");
              this.Property(t => t.ThumbnailPhotoFileName).HasColumnName("ThumbnailPhotoFileName").HasMaxLength(50);
              this.Property(t => t.rowguid).HasColumnName("rowguid");
              this.Property(t => t.ModifiedDate).HasColumnName("ModifiedDate");
              this.HasOptional(t => t.ProductCategory).WithMany(t => t.Product).HasForeignKey(d => d.ProductCategoryID);
              this.HasOptional(t => t.ProductModel).WithMany(t => t.Product).HasForeignKey(d => d.ProductModelID);
         }
    }
}
