//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksLT.Data.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class SalesOrderHeader_Mapping : EntityTypeConfiguration<SalesOrderHeader>
    {
        public SalesOrderHeader_Mapping()
        {                        
              this.HasKey(t => t.SalesOrderID);        
              this.ToTable("SalesOrderHeader", "SalesLT");
              this.Property(t => t.SalesOrderID).HasColumnName("SalesOrderID");
              this.Property(t => t.RevisionNumber).HasColumnName("RevisionNumber");
              this.Property(t => t.OrderDate).HasColumnName("OrderDate");
              this.Property(t => t.DueDate).HasColumnName("DueDate");
              this.Property(t => t.ShipDate).HasColumnName("ShipDate");
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.OnlineOrderFlag).HasColumnName("OnlineOrderFlag");
              this.Property(t => t.SalesOrderNumber).HasColumnName("SalesOrderNumber").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.Computed)).IsRequired().HasMaxLength(25);
              this.Property(t => t.PurchaseOrderNumber).HasColumnName("PurchaseOrderNumber").HasMaxLength(25);
              this.Property(t => t.AccountNumber).HasColumnName("AccountNumber").HasMaxLength(15);
              this.Property(t => t.CustomerID).HasColumnName("CustomerID");
              this.Property(t => t.ShipToAddressID).HasColumnName("ShipToAddressID");
              this.Property(t => t.BillToAddressID).HasColumnName("BillToAddressID");
              this.Property(t => t.ShipMethod).HasColumnName("ShipMethod").IsRequired().HasMaxLength(50);
              this.Property(t => t.CreditCardApprovalCode).HasColumnName("CreditCardApprovalCode").IsUnicode(false).HasMaxLength(15);
              this.Property(t => t.SubTotal).HasColumnName("SubTotal");
              this.Property(t => t.TaxAmt).HasColumnName("TaxAmt");
              this.Property(t => t.Freight).HasColumnName("Freight");
              this.Property(t => t.TotalDue).HasColumnName("TotalDue").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.Computed));
              this.Property(t => t.Comment).HasColumnName("Comment");
              this.Property(t => t.rowguid).HasColumnName("rowguid");
              this.Property(t => t.ModifiedDate).HasColumnName("ModifiedDate");
              this.HasOptional(t => t.Address).WithMany(t => t.SalesOrderHeader).HasForeignKey(d => d.BillToAddressID);
              this.HasOptional(t => t.Address1).WithMany(t => t.SalesOrderHeader1).HasForeignKey(d => d.ShipToAddressID);
              this.HasRequired(t => t.Customer).WithMany(t => t.SalesOrderHeader).HasForeignKey(d => d.CustomerID);
         }
    }
}

