//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksLT.Data.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class SalesOrderDetail_Mapping : EntityTypeConfiguration<SalesOrderDetail>
    {
        public SalesOrderDetail_Mapping()
        {                        
              this.HasKey(t => new {t.SalesOrderID, t.SalesOrderDetailID});        
              this.ToTable("SalesOrderDetail", "SalesLT");
              this.Property(t => t.SalesOrderID).HasColumnName("SalesOrderID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.SalesOrderDetailID).HasColumnName("SalesOrderDetailID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.Identity));
              this.Property(t => t.OrderQty).HasColumnName("OrderQty");
              this.Property(t => t.ProductID).HasColumnName("ProductID");
              this.Property(t => t.UnitPrice).HasColumnName("UnitPrice");
              this.Property(t => t.UnitPriceDiscount).HasColumnName("UnitPriceDiscount");
              this.Property(t => t.LineTotal).HasColumnName("LineTotal").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.Computed));
              this.Property(t => t.rowguid).HasColumnName("rowguid");
              this.Property(t => t.ModifiedDate).HasColumnName("ModifiedDate");
              this.HasRequired(t => t.Product).WithMany(t => t.SalesOrderDetail).HasForeignKey(d => d.ProductID);
              this.HasRequired(t => t.SalesOrderHeader).WithMany(t => t.SalesOrderDetail).HasForeignKey(d => d.SalesOrderID);
         }
    }
}
