using System.Collections.Generic;
using FluentJqGrid.Core.Search;

namespace FluentJqGrid.Core
{
    internal class GridOptions
    {
        internal string AjaxGridOptions { get; set; }
        internal string AjaxSelectOptions { get; set; }
        internal string AltClass { get; set; }
        internal bool? AltRows { get; set; }
        internal bool? AutoEncode { get; set; }
        internal bool? AutoWidth { get; set; }
        internal string Caption { get; set; }
        internal int? CellLayout { get; set; }
        internal bool? CellEdit { get; set; }
        internal CellSubmitType? CellSubmit { get; set; }
        internal string CellUrl { get; set; }
        internal string CmTemplate { get; set; }
        internal List<GridColumnOptions> Columns { get; set; }
        internal string Data { get; set; }
        internal string DataStr { get; set; }
        internal string DataType { get; set; }
        internal bool? DeepEmpty { get; set; }
        internal bool? DeselectAfterSort { get; set; }
        internal string Direction { get; set; }
        internal string EditUrl { get; set; }
        internal string EmptyRecords { get; set; }
        internal Events Events { get; set; }
        internal bool? ExpandColClick { get; set; }
        internal string ExpandColumn { get; set; }
        internal FilterToolbarOptions FilterToolbar { get; set; }
        internal bool? FooterRow { get; set; }
        internal bool? ForceFit { get; set; }
        internal string GridState { get; set; }
        internal bool? GridView { get; set; }
        internal bool? Grouping { get; set; }
        internal bool? HeaderTitles { get; set; }
        internal string Height { get; set; }
        internal bool? HiddenGrid { get; set; }
        internal bool? HideGrid { get; set; }
        internal bool? HoverRows { get; set; }
        internal string IdPrefix { get; set; }
        internal bool? IgnoreCase { get; set; }
        internal string ImgPath { get; set; }
        internal string InlineData { get; set; }
        internal string JsonReader { get; set; }
        internal int? LastPage { get; set; }
        internal int? LastSort { get; set; }
        internal bool? LoadOnce { get; set; }
        internal string LoadText { get; set; }
        internal string LoadUi { get; set; }
        internal FormEditingOptions FormEditingOptions { get; set; }
        internal List<InlineEditingOptions> InlineEditingOptions { get; set; }
        internal string MType { get; set; }
        internal string MultiKey { get; set; }
        internal bool? MultiBoxOnly { get; set; }
        internal bool? MultiSelect { get; set; }
        internal int? MultiSelectWidth { get; set; }
        internal NavigatorOptions NavigatorOptions { get; set; }
        internal string Page { get; set; }
        internal string Pager { get; set; }
        internal string PagerPosition { get; set; }
        internal bool? PgButtons { get; set; }
        internal bool? PgInput { get; set; }
        internal string PgText { get; set; }
        internal string PrmNames { get; set; }
        internal string PostData { get; set; }
        internal int? Reccount { get; set; }
        internal string RecordPosition { get; set; }
        internal int? Records { get; set; }
        internal string RecordText { get; set; }
        internal string ResizeClass { get; set; }
        internal int[] RowList { get; set; }
        internal bool? RowNumbers { get; set; }
        internal int? RowNum { get; set; }
        internal int? RowTotal { get; set; }
        internal int? RowNumWidth { get; set; }
        internal string SavedRow { get; set; }
        internal bool? Scroll { get; set; }
        internal int? ScrollOffset { get; set; }
        internal int? ScrollTimeout { get; set; }
        internal bool? ScrollRows { get; set; }
        internal SearchGridOptions SearchGrid { get; set; }
        internal string SelArrrow { get; set; }
        internal string SelRow { get; set; }
        internal bool? ShrinkToFit { get; set; }
        internal bool? Sortable { get; set; }
        internal string SortName { get; set; }
        internal string SortOrder { get; set; }
        internal bool? SubGrid { get; set; }
        internal string SubGridOptions { get; set; }
        internal string SubGridModel { get; set; }
        internal string SubGridType { get; set; }
        internal string SubGridUrl { get; set; }
        internal int? SubGridWidth { get; set; }
        internal string Toolbar { get; set; }
        internal bool? TopPager { get; set; }
        internal int? TotalTime { get; set; }
        internal string TreeDataType { get; set; }
        internal bool? TreeGrid { get; set; }
        internal string TreeGridModel { get; set; }
        internal string TreeIcons { get; set; }
        internal string TreeReader { get; set; }
        internal int? TreeRootLevel { get; set; }
        internal string Url { get; set; }
        internal string UserData { get; set; }
        internal bool? UserDataOnFooter { get; set; }
        internal bool? ViewRecords { get; set; }
        internal string ViewSortCols { get; set; }
        internal string Width { get; set; }
        internal string XmlReader { get; set; }
        internal string Name { get; set; }
    }
}